## A notebook to preprocess STORM data

In [5]:
# install and import libraries
%pip install pandas

import pandas as pd

Requirement already satisfied: pandas in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from pandas) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
# load data
df = pd.read_csv(
    "data/Probe1_ORF1p-647sl_data_export_100nm_10pt.csv")

df

,image-ID,cycle,z-step,frame,accum,photon-count,photon-count11,photon-count12,photon-count21,photon-count22,...,log-likelihood,accuracy,llr,time-point,cluster-ID,precisionx,precisiony,precisionz,frame-timestamp,vis-probe
0,454,0,2,54,1,1982.39,448.952,1533.440,0,0,...,-926.553,250.00,1188.010,0,57,8.78964,9.93637,41.3336,0,0
1,518,0,2,118,1,1807.05,398.383,1408.670,0,0,...,-917.350,250.00,1107.450,0,54,9.40081,10.69460,45.9148,0,0
2,589,0,2,189,1,1831.32,416.867,1414.450,0,0,...,-908.999,250.00,900.321,0,42,10.18740,11.66070,48.9057,0,0
3,590,0,2,190,1,1849.01,397.793,1451.220,0,0,...,-903.580,250.00,1116.830,0,42,9.10331,10.35100,43.8288,0,0
4,600,0,3,0,1,2333.30,560.687,1772.610,0,0,...,-943.005,230.99,1647.980,0,1245,7.22337,7.81007,35.1156,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31222,29198,0,145,198,1,1255.83,788.455,467.371,0,0,...,-937.090,250.00,597.464,0,2,15.49500,15.26680,42.9017,0,0
31223,29199,0,145,199,1,1254.38,799.747,454.635,0,0,...,-920.031,250.00,508.316,0,2,15.51840,15.31010,39.8756,0,0
31224,29211,0,146,11,1,1412.31,823.388,588.918,0,0,...,-911.448,250.00,493.236,0,2,15.00240,14.82390,48.5320,0,0
31225,29215,0,146,15,1,1028.53,588.489,440.040,0,0,...,-921.753,250.00,524.464,0,2,17.30870,17.11030,48.8434,0,0
31226,29219,0,146,19,1,1368.53,783.234,585.296,0,0,...,-946.943,250.00,499.698,0,2,18.62640,18.31810,46.2892,0,0

In [7]:
# keep only relevant columns
df_filtered = df[['x', 'y', 'z']]

df_filtered.loc[:,"Cell Type"] = "No Cell Type"
df_filtered

C:\Users\abueckle\AppData\Local\Temp\1\ipykernel_9056\978096714.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered.loc[:,"Cell Type"] = "No Cell Type"

             x         y          z     Cell Type
0      30014.0  13923.00    853.534  No Cell Type
1      36725.9  14086.20    851.323  No Cell Type
2      26357.8   3755.73    871.586  No Cell Type
3      26337.2   3759.83    854.928  No Cell Type
4      33869.3  20214.50    865.554  No Cell Type
...        ...       ...        ...           ...
31222  30637.3  33685.60  14337.000  No Cell Type
31223  30641.5  33712.60  14377.800  No Cell Type
31224  30679.8  33697.60  14383.600  No Cell Type
31225  30629.7  33647.40  14432.600  No Cell Type
31226  30649.8  33679.80  14495.400  No Cell Type

[31227 rows x 4 columns]

In [8]:
# export
df_filtered.to_csv(
    "output/Probe1_ORF1p-647sl_data_export_100nm_10pt_processed.csv", index=False)