## HRA Hierarchical Tissue Unit Annotation

In this notebook, we will build on [an existing one on hierarchical tissue unit annotation](https://github.com/HickeyLab/Hierarchical-Tissue-Unit-Annotation) by [Dr. John Hickey](https://bme.duke.edu/people/john-hickey/). Outputs from this workbook are featured in Fig. 3 in the paper titled "Human BioMolecular Atlas Program (HuBMAP): 3D Human Reference Atlas Construction and Usage" (accepted for publication in Nature Methods, see preprint [on bioRxiv](https://doi.org/10.1101/2024.03.27.587041)). In this notebook, we will create a Vasculature Common Coordinate Framework (VCCF) distance visualization for the same donor and region (B006, proximal jejunum) as in the paper, see below.

<img src="images/fig_3_original.jpg" width="400">

Concretely, we will take the original CSV file from Dryad with cell positions, types, donor IDs, and extraction sites, and then create a node-dist-vis widget plus a Cell Distance Explorer widget. For more information and documentation on hra-jupyter-widgets, please see [https://github.com/x-atlas-consortia/hra-jupyter-widgets/blob/main/usage.ipynb](https://github.com/x-atlas-consortia/hra-jupyter-widgets/blob/main/usage.ipynb).

## Load libraries

In [1]:
# Import native packages
import os
from pprint import pprint
import csv

In [2]:
#Install and import external packages
%pip install matplotlib pandas ipywidgets hra_jupyter_widgets

import matplotlib.pyplot as plt
import pandas as pd
import ipywidgets as widgets

# Import hra-jupyter-widgets. For documentation, please see https://github.com/x-atlas-consortia/hra-jupyter-widgets/blob/main/usage.ipynb
from hra_jupyter_widgets import CdeVisualization

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (3.10.0)
Requirement already satisfied: pandas in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (2.2.3)
Requirement already satisfied: ipywidgets in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (8.1.7)
Requirement already satisfied: hra_jupyter_widgets in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (0.4.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from matplotlib) (2.2.3)
Requirement already satisfied: packaging>=20.0 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: comm>=0.1.3 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from ipywidgets) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from ipywidgets) (8.32.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from ipywidgets) (4.0.14)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from ipywidgets) (3.0.15)
Requirement already satisfied: anywidget in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from hra_jupyter_widgets) (0.9.18)
Requirement already satisfied: colorama in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: decorator in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.50)
Requirement already satisfied: pygments>=2.4.0 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.19.1)
Requirement already satisfied: stack_data in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: six>=1.5 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: psygnal>=0.8.1 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from anywidget->hra_jupyter_widgets) (0.13.0)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from anywidget->hra_jupyter_widgets) (4.12.2)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)
Requirement already satisfied: wcwidth in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\abueckle\documents\github\hra-organ-gallery-in-vr-preprocessing\.venv\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

## Download data from Dryad

Let's get the data from Dryad. Note that this is a ~3GB file. We will use `curl` to dowload it.

In [3]:
# Make sure the data folder is present
folder_path = "data/"
output_path = "output/"

if not os.path.exists(folder_path):
    os.makedirs(folder_path)
    print(f"Folder '{folder_path}' created.")
else:
    print(f"Folder '{folder_path}' already exists.")
    
if not os.path.exists(output_path):
  os.makedirs(output_path)
  print(f"Folder '{output_path}' created.")
else:
    print(f"Folder '{output_path}' already exists.")

# Define the path to the file. 
file_path = f'{folder_path}/23_09_CODEX_HuBMAP_alldata_Dryad_merged.csv'

# Check if the file exists
if not os.path.exists(file_path):
    # If the file doesn't exist, run the curl command
    !curl -L https://datadryad.org/api/v2/files/2572152/download -o {file_path}
    print(f"File downloaded and saved at {file_path}")
else:
    print(f"File already exists at {file_path}")

Folder 'data/' created.
Folder 'output/' created.
File downloaded and saved at data//23_09_CODEX_HuBMAP_alldata_Dryad_merged.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0 2775M    0 68909    0     0  98766      0  8:11:08 --:--:--  8:11:08 98766
  0 2775M    0 7812k    0     0  4504k      0  0:10:31  0:00:01  0:10:30 7475k
  0 2775M    0 12.1M    0     0  4628k      0  0:10:14  0:00:02  0:10:12 6209k
  0 2775M    0 17.4M    0     0  4859k      0  0:09:44  0:00:03  0:09:41 5970k
  0 2775M    0 23.7M    0     0  5141k      0  0:09:12  0:00:04  0:09:08 6015k
  1 2775M    1 39.5M    0     0  7112k      0  0:06:39  0:00:05  0:06:34 8091k
  1 2775M    1 51.5M    0     0  7844k      0  0:06:02  0:00:06  0:05:56 9005k
  2 2775M    2 60.3M    0     0  8044k      0  0:05:53  0:00:07  0:05:46 9885k
  2 2775M    2 70.4M    0     0  8289k      0  0:05:42  0:00:08  0:05:34 10.5M
  2 2775M    2 78.0M    0     0  8231k      0  0:05:45  0:00:09  0:05:36 10.9M
  2 2775M    2 83.1M    0     0  7974k      0  0:05:56  0:00:10  0:05:46 8959k
  3 2775M    3 89.0M    0     0  7792k      0  0:06:04  0:00:11  0:05:53 7721k
  3 2775M    3 94.8M    0     0  7659k      0  0:06:11  0:00:12  0:05:59 7065k
  3 2775M    3  100M    0     0  7549k      0  0:06:16  0:00:13  0:06:03 6258k
  3 2775M    3  106M    0     0  7446k      0  0:06:21  0:00:14  0:06:07 5914k
  4 2775M    4  112M    0     0  7355k      0  0:06:26  0:00:15  0:06:11 6035k
  4 2775M    4  118M    0     0  7295k      0  0:06:29  0:00:16  0:06:13 6129k
  4 2775M    4  125M    0     0  7244k      0  0:06:32  0:00:17  0:06:15 6194k
  4 2775M    4  131M    0     0  7202k      0  0:06:34  0:00:18  0:06:16 6251k
  4 2775M    4  138M    0     0  7195k      0  0:06:35  0:00:19  0:06:16 6458k
  5 2775M    5  145M    0     0  7212k      0  0:06:34  0:00:20  0:06:14 6761k
  5 2775M    5  153M    0     0  7266k      0  0:06:31  0:00:21  0:06:10 7167k
  5 2775M    5  163M    0     0  7378k      0  0:06:25  0:00:22  0:06:03 7853k
  6 2775M    6  174M    0     0  7527k      0  0:06:17  0:00:23  0:05:54 8739k
  6 2775M    6  184M    0     0  7645k      0  0:06:11  0:00:24  0:05:47 9406k
  6 2775M    6  194M    0     0  7742k      0  0:06:07  0:00:25  0:05:42 9934k
  7 2775M    7  205M    0     0  7886k      0  0:06:00  0:00:26  0:05:34 10.3M
  7 2775M    7  217M    0     0  8038k      0  0:05:53  0:00:27  0:05:26 10.7M
  8 2775M    8  229M    0     0  8202k      0  0:05:46  0:00:28  0:05:18 11.1M
  8 2775M    8  242M    0     0  8372k      0  0:05:39  0:00:29  0:05:10 11.7M
  9 2775M    9  254M    0     0  8485k      0  0:05:34  0:00:30  0:05:04 12.0M
  9 2775M    9  263M    0     0  8528k      0  0:05:33  0:00:31  0:05:02 11.6M
  9 2775M    9  273M    0     0  8576k      0  0:05:31  0:00:32  0:04:59 11.2M
 10 2775M   10  284M    0     0  8647k      0  0:05:28  0:00:33  0:04:55 10.9M
 10 2775M   10  295M    0     0  8717k      0  0:05:26  0:00:34  0:04:52 10.5M
 11 2775M   11  305M    0     0  8779k      0  0:05:23  0:00:35  0:04:48 10.3M
 11 2775M   11  317M    0     0  8851k      0  0:05:21  0:00:36  0:04:45 10.6M
 11 2775M   11  328M    0     0  8917k      0  0:05:18  0:00:37  0:04:41 10.8M
 12 2775M   12  338M    0     0  8969k      0  0:05:16  0:00:38  0:04:38 10.8M
 12 2775M   12  350M    0     0  9032k      0  0:05:14  0:00:39  0:04:35 10.9M
 13 2775M   13  360M    0     0  9086k      0  0:05:12  0:00:40  0:04:32 11.0M
 13 2775M   13  369M    0     0  9088k      0  0:05:12  0:00:41  0:04:31 10.5M
 13 2775M   13  379M    0     0  9096k      0  0:05:12  0:00:42  0:04:30 10.2M
 14 2775M   14  389M    0     0  9125k      0  0:05:11  0:00:43  0:04:28 10.0M
 14 2775M   14  397M    0     0  9100k      0  0:05:12  0:00:44  0:04:28 9640k
 14 2775M   14  402M    0     0  9025k      0  0:05:14  0:00:45  0:04:29 8532k
 14 2775M   14  408M    0     0  8967k      0  0:05:16  0:00:46  0:04:30 7956k
 14 2775M   14  415M    0     0  8916k      0  0:05:18  0:00:47  0:04:31 7383k
 15 2775M   15  421M    0     0  8866k      0  0:05:20  0:00:48  0:04:32 6616k
 15 2775M   15  427M    0     0  8821k      0  0:05:22  0:00:49  0:04:33 6318k
 15 2775M   15  434M    0     0  8776k      0  0:05:23  0:00:50  0:04:33 6489k
 15 2775M   15  440M    0     0  8732k      0  0:05:25  0:00:51  0:04:34 6538k
 16 2775M   16  447M    0     0  8695k      0  0:05:26  0:00:52  0:04:34 6589k
 16 2775M   16  452M    0     0  8640k      0  0:05:28  0:00:53  0:04:35 6420k
 16 2775M   16  458M    0     0  8580k      0  0:05:31  0:00:54  0:04:37 6199k
 16 2775M   16  464M    0     0  8538k      0  0:05:32  0:00:55  0:04:37 6137k
 16 2775M   16  470M    0     0  8504k      0  0:05:34  0:00:56  0:04:38 6154k
 17 2775M   17  477M    0     0  8475k      0  0:05:35  0:00:57  0:04:38 6158k
 17 2775M   17  484M    0     0  8447k      0  0:05:36  0:00:58  0:04:38 6384k
 17 2775M   17  490M    0     0  8419k      0  0:05:37  0:00:59  0:04:38 6648k
 17 2775M   17  497M    0     0  8395k      0  0:05:38  0:01:00  0:04:38 6785k
 18 2775M   18  503M    0     0  8367k      0  0:05:39  0:01:01  0:04:38 6808k
 18 2775M   18  510M    0     0  8346k      0  0:05:40  0:01:02  0:04:38 6855k
 18 2775M   18  516M    0     0  8310k      0  0:05:41  0:01:03  0:04:38 6701k
 18 2775M   18  521M    0     0  8261k      0  0:05:44  0:01:04  0:04:40 6378k
 18 2775M   18  526M    0     0  8203k      0  0:05:46  0:01:05  0:04:41 5868k
 19 2775M   19  530M    0     0  8145k      0  0:05:48  0:01:06  0:04:42 5415k
 19 2775M   19  535M    0     0  8098k      0  0:05:50  0:01:07  0:04:43 4991k
 19 2775M   19  540M    0     0  8053k      0  0:05:52  0:01:08  0:04:44 4771k
 19 2775M   19  545M    0     0  8012k      0  0:05:54  0:01:09  0:04:45 4793k
 19 2775M   19  550M    0     0  7968k      0  0:05:56  0:01:10  0:04:46 4899k
 19 2775M   19  554M    0     0  7924k      0  0:05:58  0:01:11  0:04:47 4975k
 20 2775M   20  558M    0     0  7869k      0  0:06:01  0:01:12  0:04:49 4769k
 20 2775M   20  562M    0     0  7817k      0  0:06:03  0:01:13  0:04:50 4600k
 20 2775M   20  565M    0     0  7755k      0  0:06:06  0:01:14  0:04:52 4176k
 20 2775M   20  569M    0     0  7700k      0  0:06:09  0:01:15  0:04:54 3909k
 20 2775M   20  572M    0     0  7650k      0  0:06:11  0:01:16  0:04:55 3720k
 20 2775M   20  576M    0     0  7599k      0  0:06:13  0:01:17  0:04:56 3678k
 20 2775M   20  579M    0     0  7544k      0  0:06:16  0:01:18  0:04:58 3500k
 20 2775M   20  582M    0     0  7485k      0  0:06:19  0:01:19  0:05:00 3451k
 21 2775M   21  585M    0     0  7426k      0  0:06:22  0:01:20  0:05:02 3259k
 21 2775M   21  587M    0     0  7368k      0  0:06:25  0:01:21  0:05:04 3049k
 21 2775M   21  590M    0     0  7311k      0  0:06:28  0:01:22  0:05:06 2841k
 21 2775M   21  593M    0     0  7258k      0  0:06:31  0:01:23  0:05:08 2751k
 21 2775M   21  595M    0     0  7205k      0  0:06:34  0:01:24  0:05:10 2761k
 21 2775M   21  598M    0     0  7159k      0  0:06:37  0:01:25  0:05:12 2848k
 21 2775M   21  602M    0     0  7114k      0  0:06:39  0:01:26  0:05:13 2944k
 21 2775M   21  605M    0     0  7071k      0  0:06:41  0:01:27  0:05:14 3090k
 21 2775M   21  609M    0     0  7033k      0  0:06:44  0:01:28  0:05:16 3273k
 22 2775M   22  612M    0     0  6998k      0  0:06:46  0:01:29  0:05:17 3479k
 22 2775M   22  617M    0     0  6977k      0  0:06:47  0:01:30  0:05:17 3860k
 22 2775M   22  623M    0     0  6967k      0  0:06:47  0:01:31  0:05:16 4420k
 22 2775M   22  631M    0     0  6978k      0  0:06:47  0:01:32  0:05:15 5352k
 22 2775M   22  638M    0     0  6975k      0  0:06:47  0:01:33  0:05:14 5940k
 23 2775M   23  644M    0     0  6970k      0  0:06:47  0:01:34  0:05:13 6454k
 23 2775M   23  649M    0     0  6955k      0  0:06:48  0:01:35  0:05:13 6570k
 23 2775M   23  656M    0     0  6948k      0  0:06:49  0:01:36  0:05:13 6610k
 23 2775M   23  662M    0     0  6941k      0  0:06:49  0:01:37  0:05:12 6247k
 24 2775M   24  668M    0     0  6937k      0  0:06:49  0:01:38  0:05:11 6227k
 24 2775M   24  674M    0     0  6931k      0  0:06:50  0:01:39  0:05:11 6208k
 24 2775M   24  681M    0     0  6929k      0  0:06:50  0:01:40  0:05:10 6424k
 24 2775M   24  687M    0     0  6923k      0  0:06:50  0:01:41  0:05:09 6441k
 25 2775M   25  694M    0     0  6922k      0  0:06:50  0:01:42  0:05:08 6549k
 25 2775M   25  700M    0     0  6919k      0  0:06:50  0:01:43  0:05:07 6571k
 25 2775M   25  705M    0     0  6902k      0  0:06:51  0:01:44  0:05:07 6318k
 25 2775M   25  711M    0     0  6887k      0  0:06:52  0:01:45  0:05:07 6059k
 25 2775M   25  715M    0     0  6867k      0  0:06:53  0:01:46  0:05:07 5719k
 25 2775M   25  720M    0     0  6847k      0  0:06:55  0:01:47  0:05:08 5322k
 26 2775M   26  724M    0     0  6828k      0  0:06:56  0:01:48  0:05:08 4934k
 26 2775M   26  729M    0     0  6809k      0  0:06:57  0:01:49  0:05:08 4884k
 26 2775M   26  734M    0     0  6793k      0  0:06:58  0:01:50  0:05:08 4771k
 26 2775M   26  738M    0     0  6774k      0  0:06:59  0:01:51  0:05:08 4793k
 26 2775M   26  743M    0     0  6758k      0  0:07:00  0:01:52  0:05:08 4832k
 26 2775M   26  748M    0     0  6742k      0  0:07:01  0:01:53  0:05:08 4867k
 27 2775M   27  753M    0     0  6730k      0  0:07:02  0:01:54  0:05:08 4978k
 27 2775M   27  758M    0     0  6710k      0  0:07:03  0:01:55  0:05:08 4888k
 27 2775M   27  762M    0     0  6693k      0  0:07:04  0:01:56  0:05:08 4875k
 27 2775M   27  767M    0     0  6680k      0  0:07:05  0:01:57  0:05:08 4917k
 27 2775M   27  772M    0     0  6667k      0  0:07:06  0:01:58  0:05:08 4967k
 28 2775M   28  777M    0     0  6651k      0  0:07:07  0:01:59  0:05:08 4830k
 28 2775M   28  781M    0     0  6632k      0  0:07:08  0:02:00  0:05:08 4833k
 28 2775M   28  786M    0     0  6613k      0  0:07:09  0:02:01  0:05:08 4774k
 28 2775M   28  790M    0     0  6596k      0  0:07:10  0:02:02  0:05:08 4637k
 28 2775M   28  795M    0     0  6582k      0  0:07:11  0:02:03  0:05:08 4555k
 28 2775M   28  799M    0     0  6563k      0  0:07:13  0:02:04  0:05:09 4464k
 28 2775M   28  803M    0     0  6546k      0  0:07:14  0:02:05  0:05:09 4443k
 29 2775M   29  808M    0     0  6531k      0  0:07:15  0:02:06  0:05:09 4524k
 29 2775M   29  812M    0     0  6517k      0  0:07:16  0:02:07  0:05:09 4565k
 29 2775M   29  817M    0     0  6505k      0  0:07:16  0:02:08  0:05:08 4595k
 29 2775M   29  823M    0     0  6500k      0  0:07:17  0:02:09  0:05:08 4929k
 29 2775M   29  828M    0     0  6494k      0  0:07:17  0:02:10  0:05:07 5204k
 30 2775M   30  834M    0     0  6485k      0  0:07:18  0:02:11  0:05:07 5317k
 30 2775M   30  840M    0     0  6483k      0  0:07:18  0:02:12  0:05:06 5626k
 30 2775M   30  846M    0     0  6483k      0  0:07:18  0:02:13  0:05:05 5926k
 30 2775M   30  851M    0     0  6476k      0  0:07:18  0:02:14  0:05:04 5847k
 30 2775M   30  856M    0     0  6464k      0  0:07:19  0:02:15  0:05:04 5664k
 31 2775M   31  861M    0     0  6456k      0  0:07:20  0:02:16  0:05:04 5683k
 31 2775M   31  867M    0     0  6452k      0  0:07:20  0:02:17  0:05:03 5613k
 31 2775M   31  873M    0     0  6447k      0  0:07:20  0:02:18  0:05:02 5491k
 31 2775M   31  878M    0     0  6442k      0  0:07:21  0:02:19  0:05:02 5520k
 31 2775M   31  884M    0     0  6438k      0  0:07:21  0:02:20  0:05:01 5750k
 32 2775M   32  890M    0     0  6434k      0  0:07:21  0:02:21  0:05:00 5830k
 32 2775M   32  895M    0     0  6429k      0  0:07:22  0:02:22  0:05:00 5792k
 32 2775M   32  900M    0     0  6418k      0  0:07:22  0:02:23  0:04:59 5611k
 32 2775M   32  905M    0     0  6411k      0  0:07:23  0:02:24  0:04:59 5543k
 32 2775M   32  911M    0     0  6406k      0  0:07:23  0:02:25  0:04:58 5489k
 33 2775M   33  917M    0     0  6404k      0  0:07:23  0:02:26  0:04:57 5558k
 33 2775M   33  923M    0     0  6401k      0  0:07:24  0:02:27  0:04:57 5600k
 33 2775M   33  929M    0     0  6400k      0  0:07:24  0:02:28  0:04:56 5892k
 33 2775M   33  935M    0     0  6397k      0  0:07:24  0:02:29  0:04:55 6011k
 33 2775M   33  940M    0     0  6389k      0  0:07:24  0:02:30  0:04:54 5910k
 34 2775M   34  945M    0     0  6381k      0  0:07:25  0:02:31  0:04:54 5696k
 34 2775M   34  950M    0     0  6374k      0  0:07:25  0:02:32  0:04:53 5593k
 34 2775M   34  956M    0     0  6370k      0  0:07:26  0:02:33  0:04:53 5467k
 34 2775M   34  961M    0     0  6363k      0  0:07:26  0:02:34  0:04:52 5330k
 34 2775M   34  965M    0     0  6352k      0  0:07:27  0:02:35  0:04:52 5231k
 34 2775M   34  970M    0     0  6344k      0  0:07:28  0:02:36  0:04:52 5228k
 35 2775M   35  975M    0     0  6335k      0  0:07:28  0:02:37  0:04:51 5144k
 35 2775M   35  980M    0     0  6328k      0  0:07:29  0:02:38  0:04:51 5032k
 35 2775M   35  985M    0     0  6320k      0  0:07:29  0:02:39  0:04:50 4995k
 35 2775M   35  990M    0     0  6312k      0  0:07:30  0:02:40  0:04:50 5069k
 35 2775M   35  995M    0     0  6305k      0  0:07:30  0:02:41  0:04:49 5081k
 36 2775M   36 1000M    0     0  6300k      0  0:07:31  0:02:42  0:04:49 5195k
 36 2775M   36 1006M    0     0  6296k      0  0:07:31  0:02:43  0:04:48 5270k
 36 2775M   36 1012M    0     0  6293k      0  0:07:31  0:02:44  0:04:47 5436k
 36 2775M   36 1017M    0     0  6291k      0  0:07:31  0:02:45  0:04:46 5619k
 36 2775M   36 1021M    0     0  6277k      0  0:07:32  0:02:46  0:04:46 5370k
 36 2775M   36 1025M    0     0  6263k      0  0:07:33  0:02:47  0:04:46 5058k
 37 2775M   37 1029M    0     0  6249k      0  0:07:34  0:02:48  0:04:46 4737k
 37 2775M   37 1033M    0     0  6237k      0  0:07:35  0:02:49  0:04:46 4402k
 37 2775M   37 1037M    0     0  6225k      0  0:07:36  0:02:50  0:04:46 4033k
 37 2775M   37 1041M    0     0  6214k      0  0:07:37  0:02:51  0:04:46 4108k
 37 2775M   37 1046M    0     0  6204k      0  0:07:38  0:02:52  0:04:46 4221k
 37 2775M   37 1050M    0     0  6195k      0  0:07:38  0:02:53  0:04:45 4358k
 38 2775M   38 1055M    0     0  6187k      0  0:07:39  0:02:54  0:04:45 4458k
 38 2775M   38 1060M    0     0  6182k      0  0:07:39  0:02:55  0:04:44 4700k
 38 2775M   38 1066M    0     0  6179k      0  0:07:39  0:02:56  0:04:43 5005k
 38 2775M   38 1073M    0     0  6184k      0  0:07:39  0:02:57  0:04:42 5502k
 38 2775M   38 1081M    0     0  6197k      0  0:07:38  0:02:58  0:04:40 6281k
 39 2775M   39 1091M    0     0  6217k      0  0:07:37  0:02:59  0:04:38 7287k
 39 2775M   39 1101M    0     0  6242k      0  0:07:35  0:03:00  0:04:35 8349k
 39 2775M   39 1108M    0     0  6250k      0  0:07:34  0:03:01  0:04:33 8729k
 40 2775M   40 1115M    0     0  6255k      0  0:07:34  0:03:02  0:04:32 8778k
 40 2775M   40 1123M    0     0  6265k      0  0:07:33  0:03:03  0:04:30 8667k
 40 2775M   40 1130M    0     0  6266k      0  0:07:33  0:03:04  0:04:29 8023k
 40 2775M   40 1136M    0     0  6266k      0  0:07:33  0:03:05  0:04:28 7146k
 41 2775M   41 1142M    0     0  6264k      0  0:07:33  0:03:06  0:04:27 6784k
 41 2775M   41 1146M    0     0  6257k      0  0:07:34  0:03:07  0:04:27 6329k
 41 2775M   41 1152M    0     0  6252k      0  0:07:34  0:03:08  0:04:26 5769k
 41 2775M   41 1157M    0     0  6248k      0  0:07:34  0:03:09  0:04:25 5588k
 41 2775M   41 1162M    0     0  6244k      0  0:07:35  0:03:10  0:04:25 5446k
 42 2775M   42 1168M    0     0  6242k      0  0:07:35  0:03:11  0:04:24 5407k
 42 2775M   42 1173M    0     0  6237k      0  0:07:35  0:03:12  0:04:23 5491k
 42 2775M   42 1179M    0     0  6235k      0  0:07:35  0:03:13  0:04:22 5597k
 42 2775M   42 1184M    0     0  6232k      0  0:07:36  0:03:14  0:04:22 5597k
 42 2775M   42 1189M    0     0  6225k      0  0:07:36  0:03:15  0:04:21 5467k
 43 2775M   43 1194M    0     0  6218k      0  0:07:37  0:03:16  0:04:21 5332k
 43 2775M   43 1199M    0     0  6214k      0  0:07:37  0:03:17  0:04:20 5315k
 43 2775M   43 1205M    0     0  6212k      0  0:07:37  0:03:18  0:04:19 5334k
 43 2775M   43 1211M    0     0  6210k      0  0:07:37  0:03:19  0:04:18 5366k
 43 2775M   43 1216M    0     0  6209k      0  0:07:37  0:03:20  0:04:17 5603k
 44 2775M   44 1222M    0     0  6207k      0  0:07:37  0:03:21  0:04:16 5751k
 44 2775M   44 1228M    0     0  6206k      0  0:07:37  0:03:22  0:04:15 5889k
 44 2775M   44 1234M    0     0  6204k      0  0:07:38  0:03:23  0:04:15 5901k
 44 2775M   44 1240M    0     0  6204k      0  0:07:38  0:03:24  0:04:14 5986k
 44 2775M   44 1246M    0     0  6205k      0  0:07:38  0:03:25  0:04:13 6048k
 45 2775M   45 1252M    0     0  6205k      0  0:07:37  0:03:26  0:04:11 6148k
 45 2775M   45 1257M    0     0  6202k      0  0:07:38  0:03:27  0:04:11 6032k
 45 2775M   45 1264M    0     0  6199k      0  0:07:38  0:03:28  0:04:10 6002k
 45 2775M   45 1268M    0     0  6195k      0  0:07:38  0:03:29  0:04:09 5807k
 45 2775M   45 1273M    0     0  6190k      0  0:07:39  0:03:30  0:04:09 5570k
 46 2775M   46 1278M    0     0  6186k      0  0:07:39  0:03:31  0:04:08 5381k
 46 2775M   46 1283M    0     0  6178k      0  0:07:40  0:03:32  0:04:08 5180k
 46 2775M   46 1287M    0     0  6168k      0  0:07:40  0:03:33  0:04:07 4839k
 46 2775M   46 1291M    0     0  6160k      0  0:07:41  0:03:34  0:04:07 4694k
 46 2775M   46 1296M    0     0  6153k      0  0:07:41  0:03:35  0:04:06 4605k
 46 2775M   46 1300M    0     0  6146k      0  0:07:42  0:03:36  0:04:06 4453k
 47 2775M   47 1305M    0     0  6140k      0  0:07:42  0:03:37  0:04:05 4522k
 47 2775M   47 1309M    0     0  6133k      0  0:07:43  0:03:38  0:04:05 4620k
 47 2775M   47 1314M    0     0  6128k      0  0:07:43  0:03:39  0:04:04 4755k
 47 2775M   47 1319M    0     0  6124k      0  0:07:44  0:03:40  0:04:04 4841k
 47 2775M   47 1324M    0     0  6120k      0  0:07:44  0:03:41  0:04:03 4982k
 47 2775M   47 1330M    0     0  6120k      0  0:07:44  0:03:42  0:04:02 5251k
 48 2775M   48 1337M    0     0  6124k      0  0:07:44  0:03:43  0:04:01 5732k
 48 2775M   48 1343M    0     0  6124k      0  0:07:44  0:03:44  0:04:00 5924k
 48 2775M   48 1349M    0     0  6124k      0  0:07:44  0:03:45  0:03:59 6149k
 48 2775M   48 1354M    0     0  6117k      0  0:07:44  0:03:46  0:03:58 6016k
 48 2775M   48 1357M    0     0  6107k      0  0:07:45  0:03:47  0:03:58 5539k
 49 2775M   49 1362M    0     0  6098k      0  0:07:46  0:03:48  0:03:58 4953k
 49 2775M   49 1365M    0     0  6090k      0  0:07:46  0:03:49  0:03:57 4569k
 49 2775M   49 1370M    0     0  6082k      0  0:07:47  0:03:50  0:03:57 4171k
 49 2775M   49 1374M    0     0  6074k      0  0:07:47  0:03:51  0:03:56 4124k
 49 2775M   49 1378M    0     0  6067k      0  0:07:48  0:03:52  0:03:56 4239k
 49 2775M   49 1383M    0     0  6060k      0  0:07:48  0:03:53  0:03:55 4328k
 49 2775M   49 1387M    0     0  6054k      0  0:07:49  0:03:54  0:03:55 4418k
 50 2775M   50 1392M    0     0  6050k      0  0:07:49  0:03:55  0:03:54 4568k
 50 2775M   50 1397M    0     0  6047k      0  0:07:49  0:03:56  0:03:53 4799k
 50 2775M   50 1404M    0     0  6049k      0  0:07:49  0:03:57  0:03:52 5214k
 50 2775M   50 1411M    0     0  6055k      0  0:07:49  0:03:58  0:03:51 5818k
 51 2775M   51 1418M    0     0  6062k      0  0:07:48  0:03:59  0:03:49 6412k
 51 2775M   51 1426M    0     0  6067k      0  0:07:48  0:04:00  0:03:48 6885k
 51 2775M   51 1433M    0     0  6075k      0  0:07:47  0:04:01  0:03:46 7379k
 51 2775M   51 1442M    0     0  6085k      0  0:07:47  0:04:02  0:03:45 7820k
 52 2775M   52 1451M    0     0  6097k      0  0:07:46  0:04:03  0:03:43 8073k
 52 2775M   52 1459M    0     0  6109k      0  0:07:45  0:04:04  0:03:41 8377k
 52 2775M   52 1469M    0     0  6122k      0  0:07:44  0:04:05  0:03:39 8755k
 53 2775M   53 1478M    0     0  6135k      0  0:07:43  0:04:06  0:03:37 9005k
 53 2775M   53 1485M    0     0  6141k      0  0:07:42  0:04:07  0:03:35 8841k
 53 2775M   53 1490M    0     0  6137k      0  0:07:43  0:04:08  0:03:35 8083k

## Read data as DataFrame

In [4]:
# Read the CSV file and convert it to a df
df = pd.read_csv(file_path, index_col=0)
df

,MUC2,SOX9,MUC1,CD31,Synapto,CD49f,CD15,CHGA,CDX2,ITLN1,...,Cell Type em,Cell subtype,Neighborhood,Neigh_sub,Neighborhood_Ind,NeighInd_sub,Community,Major Community,Tissue Segment,Tissue Unit
0,-0.303994,-0.163727,-0.587608,-0.212903,0.164173,-0.664863,0.049305,0.003616,-0.377532,-0.450794,...,NK,Immune,Mature Epithelial,Epithelial,Mature Epithelial,Epithelial,Plasma Cell Enriched,Immune,Mucosa,Mucosa
1,-0.301927,-0.491706,-0.500804,-0.243205,-0.142568,-0.664861,-0.182627,-0.117573,-0.182754,-0.236199,...,NK,Immune,Transit Amplifying Zone,Epithelial,Mature Epithelial,Epithelial,Mature Epithelial,Epithelial,Mucosa,Mucosa
2,-0.302206,-0.547234,-0.510705,-0.235309,-0.217185,-0.622758,-0.296486,-0.091504,-0.268055,-0.355383,...,NK,Immune,Innate Immune Enriched,Immune,Innate Immune Enriched,Immune,Innate Immune Enriched,Immune,Mucosa,Mucosa
3,-0.304219,-0.613068,-0.584499,-0.243757,-0.266696,-0.658449,-0.299027,-0.121460,-0.345381,-0.450792,...,NK,Immune,Stroma & Innate Immune,Stromal,Stroma & Innate Immune,Stromal,Stroma,Stroma,Subucosa,Submucosa
4,-0.294644,-0.615593,-0.570580,-0.247548,-0.042246,-0.642230,-0.299031,-0.121458,-0.377533,-0.450797,...,NK,Immune,Outer Follicle,Immune,Outer Follicle,Immune,Follicle,Immune,Mucosa,Mucosa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2603212,0.351916,0.693827,-0.081489,-0.240643,0.008875,0.143445,0.373710,-0.097896,0.869830,0.579653,...,CD66+ Enterocyte,Epithelial,CD66+ Mature Epithelial,Epithelial,CD66+ Mature Epithelial,Epithelial,Secretory Epithelial,Epithelial,Mucosa,Mucosa
2603213,0.233642,0.171892,0.141842,-0.236145,-0.097772,-0.099283,0.626185,-0.105545,0.092076,0.682969,...,CD66+ Enterocyte,Epithelial,CD66+ Mature Epithelial,Epithelial,CD66+ Mature Epithelial,Epithelial,Secretory Epithelial,Epithelial,Mucosa,Mucosa
2603214,-0.212237,-0.280904,-0.197833,-0.245638,-0.152563,-0.125035,0.430416,-0.105787,-0.038327,-0.173319,...,CD66+ Enterocyte,Epithelial,CD8+ T Enriched IEL,Immune,CD8+ T Enriched IEL,Immune,Mature Epithelial,Epithelial,Mucosa,Mucosa
2603215,-0.328666,0.607609,-0.180362,-0.247351,-0.143742,-0.169576,1.095596,-0.113879,0.370160,-0.133272,...,CD66+ Enterocyte,Epithelial,Transit Amplifying Zone,Epithelial,Mature Epithelial,Epithelial,CD66+ Mature Epithelial,Epithelial,Mucosa,Mucosa
2603216,0.015179,1.656635,-0.250193,-0.243560,-0.084982,0.061781,1.300252,-0.108526,1.245830,-0.063456,...,CD66+ Enterocyte,Epithelial,CD66+ Mature Epithelial,Epithelial,CD66+ Mature Epithelial,Epithelial,Mature Epithelial,Epithelial,Mucosa,Mucosa

In [5]:
# Only keep cells from one dataset by selecting 1 donor and 1 region
df_filtered = df[(df['donor'] == "B012") & (
    df['unique_region'] == "B012_Proximal jejunum")]

In [6]:
df_filtered['Cell Type'] = df_filtered['Cell Type'].astype(str) + '_Cell Type'
df_filtered['Neighborhood'] = df_filtered['Neighborhood'].astype(str) + '_Neighborhood'
df_filtered['Community'] = df_filtered['Community'].astype(str) + '_Community'
df_filtered['Tissue Unit'] = df_filtered['Tissue Unit'].astype(str) + '_Tissue Unit'

C:\Users\abueckle\AppData\Local\Temp\1\ipykernel_14892\1316168077.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Cell Type'] = df_filtered['Cell Type'].astype(str) + '_Cell Type'
C:\Users\abueckle\AppData\Local\Temp\1\ipykernel_14892\1316168077.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Neighborhood'] = df_filtered['Neighborhood'].astype(str) + '_Neighborhood'
C:\Users\abueckle\AppData\Local\Temp\1\ipykernel_14892\1316168077.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Community'] = df_filtered['Community'].astype(str) + '_Community'
C:\Users\abueckle\AppData\Local\Temp\1\ipykernel_14892\1316168077.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Tissue Unit'] = df_filtered['Tissue Unit'].astype(str) + '_Tissue Unit'

In [7]:
# Next, let's define a function that turns a DataFrame into a node list that can then be passed into the CdeVisualization or NodeDistVis widget
def make_node_list(df:pd.DataFrame, is_3d:bool = False):
  """Turn a DataFrame into a list of dicts for passing them into a HRA widget

  Args:
      df (pd.DataFrame): A DataFrame with cells
  """
  
  # If the df does not have a z-axis column, let's add one and set all cells to 0
  if not is_3d:
    df.loc[:, ('z')] = 0
  
  node_list = [{'x': row['x'], 'y': row['y'], 'z': row['z'], 'Cell Type': row['combined_info']}
                 for index, row in df.iterrows()]

  return node_list

## Next, let's make four regions and visualize a 3D tissue stack.

To showcase the 3D rendering capabilities of our `CDEVisualization` widget, we will display the same section as we showed with the `NodeDistVis` widget above, but we will show it three times with an added offset along the z-axis.

In [8]:
# Create a new data frame with values from the NodeDistVis example
df = df_filtered

# indicate the number of layers you would like to show. In our case, let's show 3.
n_layers = 4   # One layer for cell type, one for neighborhood, one for community, one for tissue unit

# Create a list to hold all the data frames
df_list = [df]

for i in range(0, n_layers-1):

  # Create a copy of this new DataFrame
  df_copy = df.copy()

  # Modify a column in the copied rows (e.g., change values in column 'B')
  df_copy['unique_region'] = f'copy_{i}'  

  # Add df_copy to list of df
  df_list.append(df_copy)
  
# Concatenate the original DataFrame with the modified copies
df_combined = pd.concat(df_list, ignore_index=True)

df_filtered_3d = df_combined

In [9]:
# Set a z-offset
offset = 2500

# Set z axis (or any other axis) by region
df_filtered_3d['z'] = df_filtered_3d['unique_region'].apply(lambda v: 0 if v == 'B012_Proximal jejunum'
                                                            else offset if v == 'copy_0'
                                                            else offset * 2 if v == 'copy_1'
                                                            else offset * 3
                                                            )

# Make new df with only x, y, z, Cell Type, and Neighborhood columns
df_cells_3d = df_filtered_3d[['x', 'y', 'z', 'Cell Type', 'Neighborhood', 'Community', 'Tissue Unit']]

cell_type_z0 = df_cells_3d[df_cells_3d['z'] == 0]['Cell Type']
neighborhood_z1 = df_cells_3d[df_cells_3d['z'] == offset]['Neighborhood']
community_z2 = df_cells_3d[df_cells_3d['z'] == offset *2]['Community']
tissueunit_z3 = df_cells_3d[df_cells_3d['z'] == offset *3]['Tissue Unit']

combined_info = pd.concat([cell_type_z0, neighborhood_z1, community_z2, tissueunit_z3])

df_cells_3d['combined_info'] = combined_info

df_cells_3d_filtered = df_cells_3d[['x', 'y', 'z', 'combined_info']]

C:\Users\abueckle\AppData\Local\Temp\1\ipykernel_14892\864382709.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cells_3d['combined_info'] = combined_info

# Display

In [10]:
node_list = make_node_list(df_cells_3d_filtered, True)
edge_list = [["Cell ID","Target ID", "X1", "Y1", "Z1", "X2", "Y2", "Z2"]] # this makes an empty edges list

In [11]:
# Finally, let's instantiate the CDEVisualization class with our node_list as parameter.
cde = CdeVisualization(
    nodes=node_list,
    node_target_key = "Cell Type",
    edges=edge_list,
)

# Display our new widget
display(cde)

CdeVisualization(age=None, color_map=None, color_map_key=None, color_map_keys=None, color_map_value_key=None, …

# Prepare data for export and use in HRA Organ Gallery

In [12]:
df_cells_3d_filtered

             x       y     z                   combined_info
0       7109.0  7160.0     0            Cycling TA_Cell Type
1       4803.0    55.0     0            Cycling TA_Cell Type
2       7203.0  7413.0     0            Cycling TA_Cell Type
3        424.0  1437.0     0            Cycling TA_Cell Type
4         93.0   344.0     0            Cycling TA_Cell Type
...        ...     ...   ...                             ...
130075  7604.0  6824.0  7500              Mucosa_Tissue Unit
130076   664.0  4597.0  7500  Muscularis externa_Tissue Unit
130077  5695.0  4301.0  7500              Mucosa_Tissue Unit
130078    61.0  3230.0  7500  Muscularis externa_Tissue Unit
130079  7063.0  2809.0  7500              Mucosa_Tissue Unit

[130080 rows x 4 columns]

In [13]:
# remove z-axis
temp = df_cells_3d_filtered.drop('z', axis=1)
df_cells_3d_filtered = temp

In [14]:
n = 10  # keep every nth row

# separate into 4 dfs
df_list = []

# get dfs
levels = ['Cell Type', 'Neighborhood', 'Community', 'Tissue Unit']

df_cells_3d_filtered

for l in levels:
  df_list.append(df_cells_3d_filtered[df_cells_3d_filtered['combined_info'].str.contains(l, case=False, na=False)][::n])

# export all
counter = 0
for df in df_list:
  appendix = ""
  last_column_name = df.columns[-1]  # Get the last column name
  file_name = f"df_{levels[counter]}.csv"  # Create a dynamic file name
  df.to_csv(f"{output_path}/{file_name}", index=False)  # Export the DataFrame to CSV
  print(f"Exported {file_name} with {len(df)} rows")
  counter = counter + 1

Exported df_Cell Type.csv with 3252 rows
Exported df_Neighborhood.csv with 3252 rows
Exported df_Community.csv with 3252 rows
Exported df_Tissue Unit.csv with 3252 rows